#!/bin/bash

echo ""
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          🚨 URGENT: FIX PERMISSIONS NOW! 🚨               ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "Your workflows show only 'screenshot' because macOS is"
echo "blocking input monitoring. This is a 2-MINUTE FIX!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 1: Opening System Settings for you..."
sleep 1

# Open Input Monitoring settings
open "x-apple.systempreferences:com.apple.preference.security?Privacy_ListenEvent"

echo "✅ System Settings opened"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 2: In the System Settings window that just opened:"
echo ""
echo "   1. Click 'Privacy & Security' (left sidebar)"
echo "   2. Scroll down to 'Input Monitoring'"
echo "   3. Look for 'Terminal' or 'Python' in the list"
echo ""
echo "   IF NOT THERE:"
echo "      → Click the '+' button"
echo "      → Navigate to /Applications/Utilities/Terminal.app"
echo "      → Click 'Open'"
echo ""
echo "   IF ALREADY THERE:"
echo "      → Toggle it OFF (uncheck)"
echo "      → Wait 1 second"
echo "      → Toggle it ON (check)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 3: Press ENTER when done, then follow instructions..."
read -p ""

echo ""
echo "✅ Great! Now CRITICAL step:"
echo ""
echo "⚠️  You MUST quit Terminal completely for changes to take effect!"
echo ""
echo "   1. Press Cmd+Q (NOT just close window!)"
echo "   2. Wait 2 seconds"
echo "   3. Open Terminal again"
echo "   4. Run:"
echo ""
echo "      cd ~/Desktop/Automato"
echo "      bash test_permissions.sh"
echo ""
echo "This will confirm if it works!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 AFTER FIXING:"
echo ""
echo "   • Workflows will capture REAL actions (click, type, hotkey)"
echo "   • OCR will detect apps and text from screenshots"
echo "   • Execution will ACTUALLY move mouse and type"
echo ""
echo "Good luck with your deadline! 🚀"
echo ""

